namespace d_exception_handling;
class Program
{
    static void Main(string[] args)
    {
        try
        {
            int[] nums = new int[5];
            nums[3] = 23;
            // nums[10] = 23;
            Console.WriteLine(nums[3]);
            // Console.WriteLine(nums[10]);
        }
        catch (System.Exception e)
        {
            Console.WriteLine("Error found" + e);
        }
    }
}
